### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by aurel-g** [Taremin/comfyui-prompt-extranetworks#3]
```
Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/comfyui-prompt-extranetworks/__init__.py", line 5, in <module>
    from .prestartup_script import on_custom_nodes_loaded
  File "/mnt/comfyui/app/custom_nodes/comfyui-prompt-extranetworks/prestartup_script.py", line 24, in <module>
    load_custom_nodes = nodes.load_custom_nodes
                        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'nodes' has no attribute 'load_custom_nodes'

Cannot import /mnt/comfyui/app/custom_nodes/comfyui-prompt-extranetworks module for custom nodes: module 'nodes' has no attribute 'load_custom_nodes'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/comfyui-prompt-extranetworks

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by Taremin** [comment]
The ComfyUI update changed the code and it was not working.
It has been fixed in f89a2d3d99bb2b2a11026aa714b8f6c93dd851b2 .

**Comment by aurel-g** [comment]
Yes it works now, thanks
